### ISSUE TITLE
add thisMonth thisYear ... to the class HaystackDateTimeRange

### ISSUE THREAD

**Issue by josevu3e** [SPIE-Worksphere/haystack-csharp#99]
I find it would be very useful, I saw those methods available in the HDateTimeRange, not sure why you didn't port it to HaystackDateTimeRange

**Comment by Breederveld** [comment]
Hi @josevu3e, these are all fairly trivial helper methods, that are fairly arbitrary in their definition (why no today or yesterday for example?) and that are not set up in a way that can be unit tested properly.
I think adding helpers for this might make sense, but imo they should be set up properly, so that they can also be unit tested correctly. You are free to add them if you want.

**Comment by Breederveld** [comment]
Hi @josevu3e, for your convenience I've created a builder with some more common date ranges, however it's quite different from the original set-up as now it also takes into account other cultures and unit testability. Please have a look at the PR and let me know if this would be helpful for you.

**Comment by josevu3e** [comment]
hi @Breederveld , thanks for the reply, sorry I forgot about this. I did look through the pull request, I think it looks alright. One thing about the `HaystackDateTime`, I notice if I do HaystackDateTime(DateTime, tz) then it somehow does not work well with the Daylight Saving (I'm in Melbourne Aus) but the HaystackDateTime(DateTimeOffset, tz) it works fine, I dig into the source code and see this function for the input DateTime
`
    public HaystackDateTime(DateTime dateTime, HaystackTimeZone timeZone)
    {
      this.Value = new DateTimeOffset(dateTime.Ticks, timeZone.TimeZoneInfo.BaseUtcOffset);
      this.TimeZone = timeZone;
    }
`
should it change to 
`
 this.Value = new DateTimeOffset(dateTime);
`
